### ISSUE TITLE
UI: Delete account: Make deleting account clearer

### ISSUE THREAD

**Issue by peletron** [berty/berty#4300] opened 2022-07-19 23:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

Android

### OS version

Android 12 / iOS 15.5

### Device

Samsung Galaxy S21+

### Steps to reproduce

1.Open app 
2.Open settings via users icon 
3.Account 
4.Delete account

### Current behavior

Actual result: Message indicating to user that account will be deleted after typing "delete" would be better to be more presentable
Either highlight word user has to type or set it under quotations
"delete" // **delete**
![Berty12](https://user-images.githubusercontent.com/105677764/179866119-9cc94745-5c5a-49c4-82b6-5cb58b915c5a.jpg)

**Comment by LFGaming** [comment] 2023-05-09 13:56
Is fixed on iOS sith berty version: v2.468.0
looks like this:
![photo_2023-05-09_15-54-21](https://github.com/berty/berty/assets/38732192/a3dc26d4-b85b-428e-8ad4-41567d078bb6)

On my Android Galaxy S20 5G with berty version: v2.466.5-dev.5 it's all bold so still confusing
Looks like this:
 
![photo_2023-05-09_15-54-27](https://github.com/berty/berty/assets/38732192/3d743f63-2cb7-41df-9c60-00726c3c3bdd)

**Comment by LFGaming** [comment] 2023-05-09 13:56
Is fixed on iOS sith berty version: v2.468.0
looks like this:
![photo_2023-05-09_15-54-21](https://github.com/berty/berty/assets/38732192/a3dc26d4-b85b-428e-8ad4-41567d078bb6)

On my Android Galaxy S20 5G with berty version: v2.466.5-dev.5 it's all bold so still confusing
Looks like this:
 
![photo_2023-05-09_15-54-27](https://github.com/berty/berty/assets/38732192/3d743f63-2cb7-41df-9c60-00726c3c3bdd)

**Comment by jefft0** [comment] 2023-06-30 14:08
Agree the **delete** word should be clarified. First, we need to merge PR https://github.com/berty/berty/pull/4637 which changes the location of the localization file. Then we can update, at least, the English words. (Bear in mind that the confirmation word as displayed for the language should be used.)

**Comment by jefft0** [comment] 2023-08-04 14:16
Look at this again after merging the push notification PR because the message localization files are moved.

**Comment by jefft0** [comment] 2024-09-27 10:10
Confirmed that "**Please type delete to confirm**" is all bold on Android, Berty v2.470.3 (May 3, 2024).

**Comment by jefft0** [comment] 2024-09-27 12:28
Revisit after React Native upgrade.

**Closed** 2024-11-21 18:14 UTC
Labels: bug, p/android, p/ios, verified
