### ISSUE TITLE
Can't connect 2 contacts using dev server

### ISSUE THREAD

**Issue by alexarsh** [berty/berty#2067] opened 2020-06-14 16:23 UTC
Following the README instructions, can add one contact, but when trying to add the second one, "Add contact" button doesn't do a thing.

<img width="1680" alt="Screen Shot 2020-06-14 at 19 19 18" src="https://user-images.githubusercontent.com/84426/84598580-6f99a100-ae74-11ea-891c-573ae7cfbdb0.png">

Does anyone knows what the problem is?

**Comment by ekelen** [comment] 2020-06-14 16:57
@n0izn0iz might have a quick answer, but maybe just for posterity:

1. Are you getting any errors (not warnings) in your browser console and/or in the grpc process logs?

2. When you navigate back to a1's Account tab, does it still show a1's account data?

**Comment by alexarsh** [comment] 2020-06-14 17:19
1.) I see the following exception in my browser:

<img width="1283" alt="Screen Shot 2020-06-14 at 20 18 23" src="https://user-images.githubusercontent.com/84426/84599649-45e47800-ae7c-11ea-9156-93e0d0505fae.png">

2.) Yes. If I navigate back to a1's Account tab, it still shows a1's account data.

**Comment by n0izn0iz** [comment] 2020-06-14 19:50
I can't reproduce the issue on latest master

**Comment by alexarsh** [comment] 2020-06-15 07:10
Just pulled the latest master code and getting this error with the same scenario:

![Screen Shot 2020-06-15 at 10 09 39](https://user-images.githubusercontent.com/84426/84627924-6b12ce00-aef0-11ea-96d3-94778cfbf430.png)

**Comment by moul** [comment] 2020-10-01 12:11
Hi, thank you for your feedback, I think this was fixed in a previous PR, please reopen and add more details if you think it needs more work.

**Closed by moul** 2020-10-01 12:11 UTC
