### ISSUE TITLE
Dev mode - Version won't be displayed after generating fake data

### ISSUE THREAD

**Issue by peletron** [berty/berty#4421] opened 2022-09-12 20:42 UTC
### Is there an existing issue for this?
* [x] I have searched the existing issues

### Berty product
Mobile app

### Berty product version
2.431.2

### OS
Android

### OS version
Android 12 

### Device
Samsung Galaxy S21+

### Steps to reproduce
1. Log in to web app
1. Navigate to settings
1. Trigger Dev mode
1. Generate fake contacts, multi-members and messages
1. Navigate back to settings page

### Current behavior
After generating fake data account user is using is now displayed as Alice. 
Settings won't show current version of app but instead will display {{version}} 
see attached image
![image](https://user-images.githubusercontent.com/105677764/189754796-4143a944-c91d-4be0-baa3-e6cfafe2826a.png)

**Comment by jefft0** [comment] 2023-09-29 14:01
@jefft0 to work with @LFGaming to try to reproduce this bug and see if it is still present.

**Comment by jefft0** [comment] 2024-01-19 13:04
Can't reproduce "generate fake contacts, multi-members and messages". This bug reportedly only affects the dev screen. Closing as can't reproduce. If it is seen again we can reopen.

**Closed by jefft0** 2024-01-19 13:04 UTC
Labels: bug, p/android
