### ISSUE TITLE
anon user gets added to every group made

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#4687] opened 2023-05-30 19:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

Android version v2.268.2.dev.2, iOS version: 2.468.3

### OS

iOS

### OS version

Android version 12 and iOS version 16.4.1

### Device

iPhone 12 mini and Samsung Galaxy S20 5G

### Steps to reproduce

1. Make a group
2. Open the group
3. Click the group settings in the top right
4. Click members
5. There is a anon#{Identifier} in the group

### Current behavior

There is a anon# user always added to every group even when you did not add them, they are also always offline.

See Image:
![photo_2023-05-30_21-23-55](https://github.com/berty/berty/assets/38732192/31894c40-745b-4cec-b6db-b21eb02f61a0)

### Expected behavior

I would expect there would not be any extra users added in the group?

**Comment by jefft0** [comment] 2023-06-02 08:57
Hello @LFGaming . I tried this on my iPhone 14 with the latest Test Flight. I can't reproduce the bug. Do you have some suggestions to reproduce it?

**Comment by jefft0** [comment] 2023-06-02 09:02
Hello again @LFGaming . In a previous (deleted) message I said that I can't reproduce the bug. But I wasn't following your steps exactly. Now I see the bug. I added the "verified" label.

**Comment by jefft0** [comment] 2023-06-17 09:54
When I build from source and run on my iPhone, this bug is fixed. But when I run TestFlight (which should be the same code), the bug is not fixed. Reopened this issue and asked @iuricmp to take a look.

**Comment by jefft0** [comment] 2023-06-19 15:37
This bug is now fixed for me on the latest TestFlight 2.468.10 (4633) . Is it fixed for you, @LFGaming ?

**Comment by LFGaming** [comment] 2023-06-19 16:06
Hi @jefft0 I can confirm that it is now fixed in the latest TestFlight version 👍

**Comment by jefft0** [comment] 2023-06-19 17:11
Thanks for checking. Closing as fixed.

**Closed by jefft0** 2023-06-19 17:11 UTC
Labels: bug, released, verified, more info needed
