### ISSUE TITLE
Crash upon enabling off grid communication

### ISSUE THREAD

**Issue by Tom342** [berty/berty#4739] opened 2023-08-01 09:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.468.13.dev.8+g

### OS

Android

### OS version

Android 13

### Device

Pixel 6a

### Steps to reproduce

1. Complete account set up
2. Go to settings in the top right (account icon)
3. Enable off-grid communication
4. Allow access
5. Swipe to main screen
6. Crash at “setup-local-ipfs” 6/13

### Current behavior

Unable to use app afterwards, crashing at “setup-local-ipfs”

### Expected behavior

Should enable off grid communication and function normally

### Other

Using google play download of app

**Comment by jefft0** [comment] 2023-08-01 09:40
Hello @Tom342 . I believe this is a duplicate of bug #4733 . Does it look like the same bug to you? It is fixed in the latest dev release but not on the App Store yet.

**Comment by Tom342** [comment] 2023-08-01 11:41
> Hello @Tom342 . I believe this is a duplicate of bug #4733 . Does it look like the same bug to you? It is fixed in the latest dev release but not on the App Store yet.

Seems so! I shall attempt to use the dev release.

**Comment by jefft0** [comment] 2023-08-01 11:47
Thanks for the feedback. We also plan a new app store release soon.
Closing as duplicate.

**Closed by jefft0** 2023-08-01 11:47 UTC
Labels: bug, more info needed

**Comment by jefft0** [comment] 2023-08-03 08:05
By the way, version v2.468.16 is released on Google Play. This should fix this issue.
