### ISSUE TITLE
[BUG]: Repeat QR code reads

### ISSUE THREAD

**Issue by OliverBrotchie** [berty/berty#3447] opened 2021-07-20 17:25 UTC
### Actual Results / Problem

Berty will rapidly and repeatedly scan and vibrate whilst held over a QR code.

### Expected Results / Possible Fix

Whilst Berty should constantly look for QR codes through the camera if it has already found a code it shouldn't continuously vibrate if the QR code is the same as the code displayed on-screen.

### Give use some context

This happened whilst scanning the QR codes provided in the #beta-qr-sharing discord channel.

Phone: One Plus Nord - AC2003
Os: Oxygen OS 11.1.1.3.AC01BA
Berty: v2.293.6

**Comment by LFGaming** [comment] 2021-07-20 17:47
This bug is known yes, it’s a duplicate of [Bug #3393](https://github.com/berty/berty/issues/3393)

**Comment by OliverBrotchie** [comment] 2021-07-20 17:50
Ah okay, thanks!

**Closed** 2022-02-09 11:10 UTC
Labels: bug
