### ISSUE TITLE
Crash in db operations

### ISSUE THREAD

**Issue by phanhuynhquy** [berty/berty#2464] opened 2020-10-11 09:19 UTC
Comment all codes that filter unstable tests in pkg/bertymessenger/service_test.go.
then run all tests in `pkg/bertymessenger` several times like `go test -race -v ./pkg/bertymessenger/... -count 10 -timeout 20m`.

Sometimes crashed in TestBroken3PeersExchange test:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21dd7a0]

goroutine 127765 [running]:
database/sql.(*Tx).grabConn(0x0, 0x389a2c0, 0xc0000c6010, 0x10, 0xc004ad21b0, 0x7fb50b531290, 0xc004ad21b0)
	/usr/local/go/src/database/sql/sql.go:2105 +0x60
database/sql.(*Tx).QueryContext(0x0, 0x389a2c0, 0xc0000c6010, 0xc0004e72b0, 0x72, 0xc004ad21e0, 0x1, 0x1, 0xc001e38e30, 0xd2b5cf, ...)
	/usr/local/go/src/database/sql/sql.go:2370 +0x70
gorm.io/gorm/callbacks.Query(0xc0035380f0)
	/home/phanquy/go/pkg/mod/gorm.io/gorm@v1.20.2/callbacks/query.go:27 +0x4d2
gorm.io/gorm.(*processor).Execute(0xc0070434c0, 0xc0035380f0)
	/home/phanquy/go/pkg/mod/gorm.io/gorm@v1.20.2/callbacks.go:101 +0x1af
gorm.io/gorm.(*DB).First(0xc0035380f0, 0x2c024c0, 0xc006d8ac40, 0xc004ad2110, 0x1, 0x1, 0xc0035380f0)
	/home/phanquy/go/pkg/mod/gorm.io/gorm@v1.20.2/finisher_api.go:75 +0x276
berty.tech/berty/v2/go/pkg/bertymessenger.(*dbWrapper).getConversationByPK(0xc006d8ac30, 0xc00433d9b0, 0x2b, 0x0, 0x0, 0xc006471868)
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/db.go:330 +0x2c7
berty.tech/berty/v2/go/pkg/bertymessenger.(*eventHandler).interactionFetchRelations(0xc0065e4d20, 0xc006d8ac30, 0xc0051cbf40, 0xd320d1, 0x2b36b40)
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/handlers.go:801 +0x90
berty.tech/berty/v2/go/pkg/bertymessenger.(*eventHandler).handleAppMessage.func1(0xc006d8ac30, 0xc006d8ac30, 0x389a2c0)
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/handlers.go:107 +0xbd
berty.tech/berty/v2/go/pkg/bertymessenger.(*dbWrapper).tx.func1(0xc003538060, 0x0, 0x0)
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/db.go:78 +0x89
gorm.io/gorm.(*DB).Transaction(0xc00701f7d0, 0xc004ad2100, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/phanquy/go/pkg/mod/gorm.io/gorm@v1.20.2/finisher_api.go:440 +0x187
berty.tech/berty/v2/go/pkg/bertymessenger.(*dbWrapper).tx(0xc004328940, 0xc0047a40c0, 0x5, 0xc007f6e5d8)
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/db.go:77 +0xd1
berty.tech/berty/v2/go/pkg/bertymessenger.(*eventHandler).handleAppMessage(0xc0065e4d20, 0xc00433d9b0, 0x2b, 0xc001e39b90, 0xc006ef51d0, 0x2b, 0x0)
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/handlers.go:106 +0x55f
berty.tech/berty/v2/go/pkg/bertymessenger.(*eventHandler).groupMetadataPayloadSent(0xc0065e4d20, 0xc003b98be0, 0xd363c2, 0xc001e39c98)
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/handlers.go:225 +0x34e
berty.tech/berty/v2/go/pkg/bertymessenger.(*eventHandler).handleMetadataEvent(0xc0065e4d20, 0xc003b98be0, 0x0, 0x0)
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/handlers.go:84 +0x49b
berty.tech/berty/v2/go/pkg/bertymessenger.(*service).subscribeToMetadata.func1(0x38aae00, 0xc007fc5820, 0xc005d9ac60)
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/service.go:255 +0xe7
created by berty.tech/berty/v2/go/pkg/bertymessenger.(*service).subscribeToMetadata
	/home/phanquy/ccwork/berty/go/pkg/bertymessenger/service.go:246 +0x2f0
FAIL	berty.tech/berty/v2/go/pkg/bertymessenger	123.695s
FAIL
```
Full test reports:
[crashed_testreport.txt](https://github.com/berty/berty/files/5360828/crashed_testreport.txt)

**Comment by aeddi** [comment] 2021-03-24 16:32
Hello, 

I can't reproduce this problem even though I have launched these two commands:
- `go test -race -v ./pkg/bertymessenger/... -count 30 -timeout 1h` -> all tests 30 times
- `go test -race -v ./pkg/bertymessenger/... -count 100000 -timeout 2m -run TestBroken3PeersExchange` -> TestBroken3PeersExchange 100,000 times

It's probably been fixed by now, I'm closing the issue.

**Closed by aeddi** 2021-03-24 16:32 UTC
